### ISSUE TITLE
Docker build - conda install hanging

### ISSUE THREAD

**Issue by markospacetech** [avanetten/yoltv4#15]
Hello I came across this repo and was hoping to run your example to learn more about yolt and yolo implementations. However when the docker build gets to ` RUN conda install -n yoltv4 \ ... packages` I get the following logs.

```
 ---> Running in e78c588b0aa8
Collecting package metadata (current_repodata.json): ...working... done
Solving environment: ...working... failed with initial frozen solve. Retrying with flexible solve.
Solving environment: ...working... failed with repodata from current_repodata.json, will retry with next repodata source.
Collecting package metadata (repodata.json): ...working... done
Solving environment: ...working...
```

UPDATE: USE CONDA-FORGE REPOS

**Comment by markospacetech** [comment]
conda forge repos and python=3 geopandas used

**Comment by Sherry6352** [comment]
> conda forge repos and python=3 geopandas used

I encountered the same issue. Could you please specify how you change the codes?

**Comment by jacksonsc007** [comment]
@markospacetech Hi, same issue but didn't fix, could you elaborate your fix?
